variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  WORKING_DIRECTORY: $(Pipeline.Workspace)/build

trigger:
- master

jobs:
- job: build_js
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '11.15.0'

  - script: |
      mkdir $(WORKING_DIRECTORY)
    displayName: 'Create build folder'

  - task: Cache@2
    displayName: 'Cache packages'
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(YARN_CACHE_FOLDER)

  - script: |
      cd app
      yarn install
    displayName: 'Install node modules'
    workingDirectory: $(WORKING_DIRECTORY)

  # - script: |
  #     cd app
  #     yarn test
  #   displayName: 'Test code'
  #   workingDirectory: $(WORKING_DIRECTORY)

  - script: |
      cd app
      yarn build
    displayName: 'Build code'
    workingDirectory: $(WORKING_DIRECTORY)
