name: PR - Candee Camp - $(date:yyyyMMdd)$(rev:.r)

pr:
  - master

pool:
  vmImage: ubuntu-16.04

variables:
  YARN_CACHE_FOLDER: "$(Pipeline.Workspace)/.yarn"

stages:
  - stage: build
    displayName: "Build"

    jobs:
      - job: buildJs
        displayName: "Build JS"

        steps:
          - task: NodeTool@0
            displayName: "Install Node"
            inputs:
              versionSpec: 11.15.0

          - task: Cache@2
            displayName: "Cache Packages"
            inputs:
              key: 'yarn | "$(Agent.OS)" | app/yarn.lock'
              path: "$(YARN_CACHE_FOLDER)"
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn

          - script: "yarn"
            workingDirectory: app
            displayName: "Install Node Packages"

          - script: "yarn build"
            workingDirectory: app
            displayName: "Build Code"

      - job: buildApi
        displayName: "Build API"

        steps:
          - task: UseDotNet@2
            displayName: "Install net core 3.1"
            inputs:
              packageType: "sdk"
              version: "3.1.x"

          - task: DotNetCoreCLI@2
            displayName: "Restore Packages"
            inputs:
              command: restore
              projects: api/CandeeCamp.API.csproj

          - task: DotNetCoreCLI@2
            displayName: "Build Code"
            inputs:
              projects: api/CandeeCamp.API.csproj

  - stage: test
    displayName: "Test"
    dependsOn: build

    jobs:
      - job: testJs
        displayName: "Test JS"

        steps:
          - task: NodeTool@0
            displayName: "Install Node"
            inputs:
              versionSpec: 11.15.0

          - task: Cache@2
            displayName: "Cache packages"
            inputs:
              key: 'yarn | "$(Agent.OS)" | app/yarn.lock'
              path: "$(YARN_CACHE_FOLDER)"
              restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn

          - script: "yarn"
            workingDirectory: app
            displayName: "Install Node Packages"

          - script: "yarn test:ci"
            workingDirectory: app
            displayName: "Test Code"
