on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy-app:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        
        - name: Make envfile
          uses: SpicyPizza/create-envfile@v1
          with:
            envkey_REACT_APP_API_URL: https://api.reclaimedapp.com/api
            envkey_REACT_APP_CLIENT_NAME: registrations
            envkey_REACT_APP_CLIENT_SECRET: ${{ secrets.REACT_APP_CLIENT_SECRET }}
            envkey_REACT_APP_CRYPTO_KEY: ${{ secrets.REACT_APP_CRYPTO_KEY }}
            envkey_REACT_APP_PAYPAL_SCRIPT_URL: https://www.paypal.com/sdk/js?client-id=
            envkey_REACT_APP_URL: https://portal.reclaimedapp.com
            envkey_REACT_APP_VERSION: $npm_package_version
            file_name: app/.env
            
        - run: |
            cd app
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/reclaimedapp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/reclaimedapp:${{ github.sha }}
       
        - uses: azure/webapps-deploy@v2
          with:
            app-name: 'reclaimedapp'
            images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/reclaimedapp:${{ github.sha }}

        - name: Azure logout
          run: |
            az logout
            
    build-and-deploy-api:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            cd api
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/reclaimedapi:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/reclaimedapi:${{ github.sha }}
       
        - uses: azure/webapps-deploy@v2
          with:
            app-name: 'reclaimed-api'
            images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/reclaimedapi:${{ github.sha }}

        - name: Azure logout
          run: |
            az logout
